### ISSUE TITLE
Select difficulty

### ISSUE THREAD

**Issue by jesskins** [rowan01g/Fission-for-Answers#28]
**User Story**
As a player, I want to be able to select from _different difficulties_, depending on how much I wish to challenge myself.

**Acceptance Criteria**

- [ ] A list of available difficulties is displayed to the player upon starting or during the game.
- [ ] Clearly labeled and visually distinct.

**Tasks**

- [ ] Design a UI element to display difficulties.
- [ ] Add visual feedback for selected difficulty.
- [ ] Create a data structure to store difficulty and associated questions.
